import type { AutonomyScenario, AutonomyIssueType } from "./autonomy.types.js";

export const AUTONOMY_SCENARIOS: AutonomyScenario[] = [
  {
    name: "PriceDropCompetitor",
    issueTypes: ["COMPETITOR_PRESSURE", "PRICING_ANOMALY"],
    inputSignals: ["competitorPriceDrop", "pricingAnomaly"],
    engines: ["PRICING_ENGINE", "FINANCE_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "pricing",
    safeActions: [
      {
        id: "price-sim",
        goal: "Simulate price response and recommend guarded move",
        engine: "PRICING_ENGINE",
        agentId: "pricing-strategist",
        safetyPath: "SAFE",
      },
      {
        id: "margin-check",
        goal: "Model revenue and margin impact of recommended move",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        dependsOn: ["price-sim"],
        safetyPath: "SAFE",
      },
      {
        id: "price-brief",
        goal: "Send advisory to finance and ops with playbook steps",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["margin-check"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "price-apply",
        goal: "Apply tactical price change with guardrails",
        engine: "PRICING_ENGINE",
        agentId: "pricing-strategist",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "price-alert",
        goal: "Notify finance and execs of action plus monitoring plan",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["price-apply"],
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "HIGH",
  },
  {
    name: "LowStockReplenishment",
    issueTypes: ["INVENTORY_RISK"],
    inputSignals: ["lowStock", "highVelocity"],
    engines: ["INVENTORY_ENGINE", "OPERATIONS_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "inventory",
    safeActions: [
      {
        id: "replenishment-plan",
        goal: "Generate replenishment plan with supplier options",
        engine: "INVENTORY_ENGINE",
        agentId: "inventory-optimizer",
        safetyPath: "SAFE",
      },
      {
        id: "ops-brief",
        goal: "Send low-stock playbook to ops for confirmation",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["replenishment-plan"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "po-draft",
        goal: "Draft purchase order and budget check",
        engine: "INVENTORY_ENGINE",
        agentId: "inventory-optimizer",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "ops-approve",
        goal: "Request approval for auto-fulfillment and allocations",
        engine: "OPERATIONS_ENGINE",
        agentId: "governance-engine",
        dependsOn: ["po-draft"],
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "HIGH",
  },
  {
    name: "MarginCollapseAlert",
    issueTypes: ["MARGIN_DROP"],
    inputSignals: ["marginCollapse", "discountSpike"],
    engines: ["FINANCE_ENGINE", "PRICING_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "finance",
    safeActions: [
      {
        id: "margin-diagnosis",
        goal: "Diagnose margin collapse and propose recovery levers",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        safetyPath: "SAFE",
      },
      {
        id: "pricing-guard",
        goal: "Recommend pricing guardrails to stop bleed",
        engine: "PRICING_ENGINE",
        agentId: "pricing-strategist",
        dependsOn: ["margin-diagnosis"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "discount-freeze",
        goal: "Freeze discounts and escalate to finance",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "exec-brief",
        goal: "Send executive summary with next steps and approvals",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["discount-freeze"],
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "CRITICAL",
  },
  {
    name: "ChurnRiskDetected",
    issueTypes: ["CRM_CHURN_RISK"],
    inputSignals: ["lowLeadScore", "dormantAccount"],
    engines: ["CRM_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "crm",
    safeActions: [
      {
        id: "save-plan",
        goal: "Draft save plan with outreach steps",
        engine: "CRM_ENGINE",
        agentId: "crm-coach",
        safetyPath: "SAFE",
      },
      {
        id: "route-owner",
        goal: "Route plan to account owner with consent-aware messaging",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["save-plan"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "offer-apply",
        goal: "Apply retention offer draft pending approval",
        engine: "CRM_ENGINE",
        agentId: "crm-coach",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "notify-lead",
        goal: "Notify sales leadership of churn cluster",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["offer-apply"],
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "HIGH",
  },
  {
    name: "MarketingROASDrop",
    issueTypes: ["MARKETING_UNDERPERFORMANCE"],
    inputSignals: ["roasDrop", "ctrCollapse"],
    engines: ["MARKETING_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "marketing",
    safeActions: [
      {
        id: "creative-audit",
        goal: "Audit creatives and recommend swaps with safe budget moves",
        engine: "MARKETING_ENGINE",
        agentId: "campaign-engine",
        safetyPath: "SAFE",
      },
      {
        id: "roas-brief",
        goal: "Share ROAS recovery plan to CMO",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["creative-audit"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "budget-shift",
        goal: "Shift budget to higher-performing ad sets",
        engine: "MARKETING_ENGINE",
        agentId: "campaign-engine",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "brand-check",
        goal: "Run brand safety validation before publish",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["budget-shift"],
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "MEDIUM",
  },
  {
    name: "PartnerRiskAlert",
    issueTypes: ["PARTNER_RISK"],
    inputSignals: ["engagementDrop", "slaBreach"],
    engines: ["PARTNER_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "partner",
    safeActions: [
      {
        id: "health-check",
        goal: "Assess partner health and propose recovery steps",
        engine: "PARTNER_ENGINE",
        agentId: "partner-ops",
        safetyPath: "SAFE",
      },
      {
        id: "partner-brief",
        goal: "Notify partner manager with intervention plan",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["health-check"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "tier-review",
        goal: "Prepare tier downgrade recommendation",
        engine: "PARTNER_ENGINE",
        agentId: "partner-ops",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "suspend-proposal",
        goal: "Draft suspension notice for legal review",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["tier-review"],
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "HIGH",
  },
  {
    name: "FinanceCashflowRisk",
    issueTypes: ["FINANCE_RISK"],
    inputSignals: ["cashflowStress", "expenseSpike"],
    engines: ["FINANCE_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "finance",
    safeActions: [
      {
        id: "cash-forecast",
        goal: "Run cashflow stress forecast and options",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        safetyPath: "SAFE",
      },
      {
        id: "collections-plan",
        goal: "Recommend collections or cost deferral actions",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        dependsOn: ["cash-forecast"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "freeze-spend",
        goal: "Propose spend freeze on non-essential vendors",
        engine: "FINANCE_ENGINE",
        agentId: "margin-engine",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "exec-finance-brief",
        goal: "Send finance risk brief with approval matrix",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["freeze-spend"],
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "CRITICAL",
  },
  {
    name: "SupportCrisisSignal",
    issueTypes: ["SUPPORT_ALERT"],
    inputSignals: ["urgentTickets", "escalations"],
    engines: ["SUPPORT_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "support",
    safeActions: [
      {
        id: "triage",
        goal: "Triage tickets and recommend responses",
        engine: "SUPPORT_ENGINE",
        agentId: "support-engine",
        safetyPath: "SAFE",
      },
      {
        id: "status-brief",
        goal: "Send crisis status to CX leadership",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["triage"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "refund-proposal",
        goal: "Propose refunds or credits with approval",
        engine: "SUPPORT_ENGINE",
        agentId: "support-engine",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "public-update",
        goal: "Draft public update for PR/legal review",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["refund-proposal"],
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "HIGH",
  },
  {
    name: "StrategyOKRDeviation",
    issueTypes: ["OPERATIONS_ALERT"],
    inputSignals: ["okrMiss", "backlog", "roadmapConflict"],
    engines: ["OPERATIONS_ENGINE", "AUTONOMY_ENGINE"],
    playbook: "strategy",
    safeActions: [
      {
        id: "okr-delta",
        goal: "Analyze OKR deviation and root causes",
        engine: "OPERATIONS_ENGINE",
        agentId: "governance-engine",
        safetyPath: "SAFE",
      },
      {
        id: "realign",
        goal: "Propose realignment plan with owners and timelines",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["okr-delta"],
        safetyPath: "SAFE",
      },
    ],
    highRiskActions: [
      {
        id: "okr-reset",
        goal: "Draft OKR reset proposal with impact",
        engine: "OPERATIONS_ENGINE",
        agentId: "governance-engine",
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
      {
        id: "board-brief",
        goal: "Send executive briefing for approval",
        engine: "AUTONOMY_ENGINE",
        agentId: "insight-reporter",
        dependsOn: ["okr-reset"],
        approvalRequired: true,
        safetyPath: "HIGH_RISK",
      },
    ],
    defaultRisk: "MEDIUM",
  },
];

export function findScenarioForIssue(issue: AutonomyIssueType): AutonomyScenario | null {
  return AUTONOMY_SCENARIOS.find((scenario) => scenario.issueTypes.includes(issue)) ?? null;
}
